# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "go-github-to-jira-unstable-${version}";
  version = "2019-09-24";
  rev = "c963ca8c68f23407b0c07bfe3ce29d13d3f4c66f";

  goPackagePath = "stash.shopware.com/tool/go-github-to-jira";

  src = fetchgit {
    inherit rev;
    url = "https://stash.shopware.com/scm/tool/go-github-to-jira.git";
    sha256 = "1a22983gnln61vzxplwbhaayk14ivj23dyhcn1hqmjba482qyqm9";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = { };
}
